#pragma once

#include "system/aiagentrandomwandersystem.h"
#include "system/animationsystem.h"
#include "system/animatorsystem.h"
#include "system/computetilesystem.h"
#include "system/dieonstopsystem.h"
#include "system/diesystem.h"
#include "system/facingrenderingsystem.h"
#include "system/hadroncollisionsystem.h"
#include "system/healthsystem.h"
#include "system/infectionsystem.h"
#include "system/mapawarenesssystem.h"
#include "system/mapnavigationsystem.h"
#include "system/placeinmapsystem.h"
#include "system/playerinputsystem.h"
#include "system/reinforcingsystem.h"
#include "system/renderingsystem.h"
#include "system/shootatsightsystem.h"
#include "system/shootingsystem.h"
#include "system/systemgroups.h"
#include "system/triggersystem.h"
#include "system/wallplacementsystem.h"

